# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Klaus\Desktop\DCOP\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
# sys.path.append('c:\\Users\\Klaus\\Desktop\\DCOP\\DCOPGenetor\\')
from PyQt5 import QtCore, QtGui, QtWidgets
from DCOPGenetor import *
import os
path = os.path.dirname(os.path.dirname(__file__))



class Ui_DCOPGenetor(object):
    def setupUi(self, DCOPGenetorr):
        DCOPGenetorr.setObjectName("DCOPGenetor")
        DCOPGenetorr.resize(595, 484)
        self.filename = None
        self.centralwidget = QtWidgets.QWidget(DCOPGenetorr)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 181, 31))
        self.label.setObjectName("label")
        self.NbInstances = QtWidgets.QSpinBox(self.centralwidget)
        self.NbInstances.setGeometry(QtCore.QRect(220, 30, 181, 22))
        self.NbInstances.setToolTipDuration(1)
        self.NbInstances.setProperty("value", 1)
        self.NbInstances.setDisplayIntegerBase(10)
        self.NbInstances.setObjectName("NbInstances")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 151, 16))
        self.label_2.setObjectName("label_2")
        self.NbAgents = QtWidgets.QSpinBox(self.centralwidget)
        self.NbAgents.setGeometry(QtCore.QRect(220, 80, 181, 22))
        self.NbAgents.setProperty("value", 5)
        self.NbAgents.setObjectName("NbAgents")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 160, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 160, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 160, 72, 15))
        self.label_6.setObjectName("label_6")
        self.GDFrom = QtWidgets.QSpinBox(self.centralwidget)
        self.GDFrom.setGeometry(QtCore.QRect(200, 190, 46, 22))
        self.GDFrom.setProperty("value", 20)
        self.GDFrom.setObjectName("GDFrom")
        self.GDStep = QtWidgets.QSpinBox(self.centralwidget)
        self.GDStep.setGeometry(QtCore.QRect(270, 190, 46, 22))
        self.GDStep.setProperty("value", 30)
        self.GDStep.setObjectName("GDStep")
        self.GDTo = QtWidgets.QSpinBox(self.centralwidget)
        self.GDTo.setGeometry(QtCore.QRect(350, 190, 46, 22))
        self.GDTo.setProperty("value", 100)
        self.GDTo.setObjectName("GDTo")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 260, 151, 16))
        self.label_7.setObjectName("label_7")
        self.MinCost = QtWidgets.QSpinBox(self.centralwidget)
        self.MinCost.setGeometry(QtCore.QRect(200, 260, 181, 22))
        self.MinCost.setProperty("value", 0)
        self.MinCost.setObjectName("MinCost")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 310, 151, 16))
        self.label_8.setObjectName("label_8")
        self.MaxCost = QtWidgets.QSpinBox(self.centralwidget)
        self.MaxCost.setGeometry(QtCore.QRect(200, 310, 181, 22))
        self.MaxCost.setProperty("value", 99)
        self.MaxCost.setObjectName("MaxCost")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 370, 71, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 370, 231, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 420, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 130, 161, 16))
        self.label_10.setObjectName("label_10")
        self.DomainSize = QtWidgets.QSpinBox(self.centralwidget)
        self.DomainSize.setGeometry(QtCore.QRect(220, 120, 181, 22))
        self.DomainSize.setProperty("value", 10)
        self.DomainSize.setObjectName("DomainSize")
        DCOPGenetorr.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DCOPGenetorr)
        self.statusbar.setObjectName("statusbar")
        DCOPGenetorr.setStatusBar(self.statusbar)

        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(440,370,93,21))
        self.pushButton_1.setObjectName("pushButton_1")


        self.GDStep.setVisible(False)
        self.GDTo.setVisible(False)
        self.pushButton_1.clicked.connect(self.openfile)
        self.retranslateUi(DCOPGenetorr)
        self.pushButton.clicked.connect(self.click)
        QtCore.QMetaObject.connectSlotsByName(DCOPGenetorr)


    def openfile(self):
        self.filename = QtWidgets.QFileDialog.getExistingDirectory(None,  
                                    "选取文件夹",  
                                    path, # 起始路径 
                                    )   # 设置文件扩展名过滤,用双分号间隔

        print(self.filename)
        self.lineEdit.setText(self.filename)



    def retranslateUi(self, DCOPGenetorr):
        _translate = QtCore.QCoreApplication.translate
        DCOPGenetorr.setWindowTitle(_translate("DCOPGenetorr", "DCOPGenetor"))
        self.label.setText(_translate("DCOPGenetorr", "Number Of Instances:"))
        self.label_2.setText(_translate("DCOPGenetorr", "Number Of Agents:"))
        self.label_3.setText(_translate("DCOPGenetorr", "Graph Density(%):"))
        #self.label_4.setText(_translate("DCOPGenetorr", "From"))
        #self.label_5.setText(_translate("DCOPGenetorr", "Step"))
        #self.label_6.setText(_translate("DCOPGenetorr", "To"))
        self.label_7.setText(_translate("DCOPGenetorr", "Minimun Cost:"))
        self.label_8.setText(_translate("DCOPGenetorr", "Maximum Cost:"))
        self.label_9.setText(_translate("DCOPGenetorr", "Path:"))
        self.pushButton.setText(_translate("DCOPGenetorr", "Generate"))
        self.label_10.setText(_translate("DCOPGenetorr", "Domain Size:"))
        self.pushButton_1.setText(_translate("DCOPGenetorr", "浏览"))



    def click(self):
        NbInstance = self.NbInstances.text()
        NbAgents = self.NbAgents.text()
        GDFrom = self.GDFrom.text()
        GDTo = self.GDTo.text()
        GDStep = self.GDStep.text()
        MinCost = self.MinCost.text()
        MaxCost = self.MaxCost.text()
        Path = self.lineEdit.text()
        domainSize = self.DomainSize.text()

        print(GDFrom)
        
        g = DCOPGenetor(Path,"TKC",int(NbInstance),int(NbAgents),int(domainSize),int(GDFrom),int(GDTo),int(GDStep),int(MinCost),int(MaxCost))
        g.generate()
        dialog=QtWidgets.QDialog()
        # btn=QtWidgets.QPushButton('ok',dialog)
        # #移动按钮，设置dialog的标题
        # btn.move(50,50)
        # dialog.setWindowTitle("Dialog")
        # #设置窗口的属性为ApplicationModal模态，用户只有关闭弹窗后，才能关闭主界面
        # dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        # dialog.exec_()

        reply = QtWidgets.QMessageBox.information(dialog, 'DCOP问题生成','生成成功',QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,QtWidgets.QMessageBox.Yes)




if __name__=="__main__":
    app=QtWidgets.QApplication(sys.argv) 
    formObj=QtWidgets.QMainWindow()  #注意，这里和我们一开始创建窗体时使用的界面类型相同  
    ui=Ui_DCOPGenetor()    
    ui.setupUi(formObj)    
    formObj.show()    
    sys.exit(app.exec_()) 


